name: third-workflow
on: push
jobs:
    tests:
        runs-on: ubuntu-latest
        steps:
            - name: download code
              uses: actions/checkout@v2
            - name: install nodejs
              uses: actions/setup-node@v2
              with:
                    node-version: '18'
            - name: install dependenciew
              uses: npm ci
            - name: run tests
              uses: npm test

              